### ISSUE TITLE
Not receiving messages after first

### ISSUE THREAD

**Issue by yasir-khilji-64** [ARMmbed/mbed-mqtt#16]
I'm using Mbed Cellular with mbed-mqtt for sending messages. The problem is, it receives the first message fine but can't get next messages. I'm sending JSON.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/ONME-4487*

**Comment by michalpasztamobica** [comment]
Hi @yasir-khilji-64 , can you please let us know:
1) What exactly is the platform you're using? Does it work fine otherwise?
2) The JSON seems missing, can you please try attaching it again?

**Comment by michalpasztamobica** [comment]
@yasir-khilji-64 , I am closing this issue, but if your issue is still there and you can provide more information, please feel free to reopen it.
