### ISSUE TITLE
Failed to send a long payload message

### ISSUE THREAD

**Issue by dadanugm** [ARMmbed/mbed-mqtt#21]
Hi Everyone,
I have mqtt publish issue on a long payload message. Everything was working fine with a short payload until I increase the message payload into > 3000 characters. I changed configuration in mbed_lib.json at max-packet-size: 16384. but still no expected result. What is probably the problem? Any suggestion?
board: Nucleo F767ZI, Mbed Os. 5.15.2
Mqtt broker: Mosquitto on raspberry pi.
Main File: 
[Mainfile.zip](https://github.com/ARMmbed/mbed-mqtt/files/4508287/Mainfile.zip)
Thanks

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/ONME-4499*

**Comment by dadanugm** [comment]
Hi @ciarmcom, your link can't be accessed 

> _Internal Jira reference: https://jira.arm.com/browse/ONME-4499_

**Comment by michalpasztamobica** [comment]
Hi @dadanugm . ciarmcom is just a bot and it has created an Internal JIRA, meaning only ARM emplyees can see it.
Just a few ideas that come to my mind... 
1) Have you tried playing with the stack/heap sizes to see if that moved the limit?
2) Can you please check the issues reported to Paho library, for example this one: https://github.com/eclipse/paho.mqtt.embedded-c/issues/136
3) Are you sure your broker doesn't have any length limits? Did you try sending long packets from a different client (not mbed-mqtt-based)?

**Comment by dadanugm** [comment]
Lol, I thought at first it was one of the engineer. :))
Solution No. 1 doing the trick, I did increase the main-stack size about 16kb. Now my code is working perfectly. Thanks for the help @michalpasztamobica
