### ISSUE TITLE
Can't receive messages longer that 512 bytes

### ISSUE THREAD

**Issue by Spinnaker-design** [ARMmbed/mbed-mqtt#24]
I'm having an issue with the MQTT library when the payload of a received message is greater that 512 bytes.  I have set the max packet size to 2048 and have the yield timeout set all the way up to 4000, but it yield() always returns -3004.  I've traced it down to: `    /* 3. read the rest of the buffer using a callback to supply the rest of the data */
    if (rem_len > 0 && (ipstack.read(readbuf + len, rem_len, timer.left_ms()) != rem_len))
    {
        rc = FAILURE;
        goto exit;
    }`
In MQTTClient.h

Which always seems to return FAILURE regardless of the settings.

I have also tried to increase my heap size. but that has had no effect.

**Comment by Spinnaker-design** [comment]
Any update's on this?  Happy to provide any details needed to help debug.

**Comment by 0xc0170** [comment]
@michalpasztamobica would you be able to help or @pan- ?

**Comment by pan-** [comment]
@paul-szczepanek-arm .

**Comment by Spinnaker-design** [comment]
Hi, anyone been able to take a look at this?  I would appreciate any guidance if it is user error.

**Comment by paul-szczepanek-arm** [comment]
Not yet, sorry.

**Comment by donatieng** [comment]
@Spinnaker-design it looks like the implementation in https://github.com/ARMmbed/mbed-mqtt/blob/2a83f4993401cca786e0843faeed82219ed9ae77/src/MQTTNetwork.h#L36 is incorrect.

Basically https://github.com/ARMmbed/mbed-mqtt/blob/2a83f4993401cca786e0843faeed82219ed9ae77/paho_mqtt_embedded_c/MQTTClient/src/MQTTClient.h#L476
expects the socket to block until the full packet is received.

However the underlying API (Mbed's `TCPSocket` class) returns when some data is available (won't block until the full packet is received):
https://github.com/ARMmbed/mbed-os/blob/aff95c0d190a5528e4704de3e281b2e52c7ae980/connectivity/netsocket/include/netsocket/TCPSocket.h#L102 

Therefore the `MQTTNetwork.h` implementation needs to be amended to call `recv()` until the full packet is received, or a timeout occurs.

**Comment by paul-szczepanek-arm** [comment]
tracked in https://jira.arm.com/browse/IOTPAN-660

**Comment by Spinnaker-design** [comment]
are there any updates on this?

**Comment by Spinnaker-design** [comment]
Sorry to keep pressing on this, but we are running into some issues in our product implementation because of this issue.  We can explore fixing it ourselves if needed, but since it's being tracked in the internal arm jira, some guidance around if / when it will be address would be good.

Is there anything you can tell me?

**Comment by 0xc0170** [comment]
Have you tried to apply https://github.com/ARMmbed/mbed-mqtt/issues/24#issuecomment-673394759 ?

**Comment by paul-szczepanek-arm** [comment]
Apologies. We had other ongoing development and this will be scheduled for next sprint next week.

**Comment by sklatham69** [comment]
Thanks.  What is a typical timeline for your sprint regarding issue resolution?

**Comment by paul-szczepanek-arm** [comment]
Our sprints are 2 weeks long. Next one starts this Thursday.

**Comment by sklatham69** [comment]
Thanks.  This is a huge issue for us.  Mbed has been great in our efforts to replace our unsupported custom OS but this particular issue has us stopped just before release.  Any and all help is appreciated.  Thanks again for your efforts.  Anxiously waiting ...

**Comment by 0xc0170** [comment]
@sklatham69 meanwhile, if you can debug or get into implementation and finding what is causing it or anything that would get us closer to fix, please write here.

**Comment by sklatham69** [comment]
Sure, any suggestions or specifics on what you may need let us know.  We're here to support and speed this up in any way necessary.

**Comment by sklatham69** [comment]
@0xc0170 Just a quick question.  We have a couple other issues with Mbed interfacing with two Microchip parts (KSZ8794 and the SST26VF016B).  @Spinnaker-design has been working on them for weeks.  They appear to be Mbed driver related ... just wondering if you know of anyone that would have time to work with us to get these issues resolved as well.  We have let this slip and it's costing us financially now.  We'd be willing work directly with anyone that could assist.  We really need these resolved in the next week.  Thanks in advance.

**Comment by Spinnaker-design** [comment]
I believe @donatieng is more or less correct, but the current implementation relies on getting a 0 from recv to detect if the client has disconnected, so that assumption may need to be revised.

**Comment by sklatham69** [comment]
Just checking if there is an update on this issue or if it was resolved in 6.3 release?  Thanks

**Comment by paul-szczepanek-arm** [comment]
Yes, there is a PR https://github.com/ARMmbed/mbed-mqtt/pull/27, I'd appreciate if you helped us review

**Comment by paul-szczepanek-arm** [comment]
@Spinnaker-design may I ask you to please try the changes in https://github.com/ARMmbed/mbed-mqtt/pull/27 ?

**Comment by Spinnaker-design** [comment]
Hi @paul-szczepanek-arm on it this morning

**Comment by pan-** [comment]
@Spinnaker-design Can we close this ?

**Comment by Spinnaker-design** [comment]
Yes

**Comment by Spinnaker-design** [comment]
Thanks a lot!
