### ISSUE TITLE
MQTT wildcard subscriptions don't work with root topic

### ISSUE THREAD

**Issue by Spinnaker-design** [ARMmbed/mbed-mqtt#25]
Wildcard subscriptions do not seem to be working per the MQTT standard.

Subscribing to '/test/topic/#' does not seem to work for messages coming into '/test/topic'.

It only seems to work for subtopics, for example:

'/test/topic/one'
and 
'/test/topic/two'

**Comment by LukaB** [comment]
Hi 

I believe I have a related issue.

Following the [tutorial](https://os.mbed.com/users/coisme/notebook/google-cloud-iot-from-mbed-os-device/) I can connect the HW to GCP no problem.
Subscribing to `/devices/{device-id}/config` works just fine and the device receives config messages.

Subscribing to `/devices/{device-id}/commands/#` works, but we never receive any command messages.
According to GCP [article ](https://cloud.google.com/iot/docs/how-tos/commands) we need to be subscribed to the wildcard topic. In fact GCP refuses to send a command if the device is not subscribed to the wildcard topic.

From what I can see the default commands are sent to `/devices/{device-id}/commands`, but we never receive them.

I have tried adding a subscription to `/devices/{device-id}/commands` as well as `/devices/{device-id}/commands/#`, but this doesn't seem to work as a workaround on mBed as it does on another toolchain I am testing.

Thanks

**Comment by LukaB** [comment]
@ciarmcom Have there been any updates on this?

**Comment by 0xc0170** [comment]
> @ciarmcom Have there been any updates on this?

It is just a bot. Someone from our team will look at this but I can't provide an estimate at the moment.

**Comment by LukaB** [comment]
@0xc0170 thank you for the update.
I believe the section of code that is causing the issues is pre-compiled in mBed.

Would it be possible for someone to have a look at this in the next few weeks? 
If not, are you able to provide me with the link to the source code of the library?
I would be more than happy to look into it.

Thanks

**Comment by 0xc0170** [comment]
It should not be precompiled. @LukaB What example are you using and how do you fetch this repository?

**Comment by LukaB** [comment]
@0xc0170 
Apologies, the source code is all there, I just didn't think to look inside the header files for the code I was after.

I have two solutions to the submitted bug. One is a workaround and the other is a permanent fix that one of your team should review and possibly publish.

The library for MQTT is "mbed-mqtt master" as imported from https://github.com/ARMmbed/mbed-mqtt/

**Current workaround:**
In the users own code, set the mqttClient default message handler.
While not ideal as it will pick up all sorts of messages, it does allow to capture all messages that are coming into the device.
Example: `mqttClient->setDefaultMessageHandler(handleMqttMessage);`

**Permanent fix:**
Within MQTTClient.h, the function 

> template<class Network, class Timer, int a, int b>
> bool MQTT::Client<Network, Timer, a, b>::isTopicMatched(char* topicFilter, MQTTString& topicName)

requires the following code to be added before we return.

> 	if(*curf != '\0')
> 	{
> 		//If our topic filter ends with a wildcard '/#' we need to account for that
> 		if((*curf == '/') && (*(curf++) == '#'))
> 			curf++;
> 	}

The above ensures that the final return statement

> return (curn == curn_end) && (*curf == '\0');

returns correctly and the wildcard topic filter is matched.


Thank you

Luka Bartolec

**Comment by LukaB** [comment]
Full code:
[MQTT_WildcardFix.txt](https://github.com/ARMmbed/mbed-mqtt/files/5185197/MQTT_WildcardFix.txt)

Thanks

Luka

**Comment by 0xc0170** [comment]
@LukaB can you create a new pull request with the fix?

**Comment by phlegx** [comment]
Any news for this problem?

**Comment by 0xc0170** [comment]
PR #26 was merged
