### ISSUE TITLE
Client get disconnected

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-mqtt#33]
Hello
My team uses the MQTT library for mbed os but we have some issues. Specifically, the MQTT library yield function not working properly and the client disconnected after 90s. Is there any solution?
Thank you in advance

**Comment by 0xc0170** [comment]
although a user is not active anymore, the bug report does not contain enough details for anyone to assist here.

**Comment by Serphentas** [comment]
I also have the behaviour explained by the reporter with mosquitto as broker. Sending messages before the timeout "solves" this issue, although the `keepalive` method from the paho library could be used somehow.
