### ISSUE TITLE
Error Compiling MQTTClientMbedOS

### ISSUE THREAD

**Issue by yasir-khilji-64** [ARMmbed/mbed-mqtt#9]
I'm having issues in Compiling the MQTT Client for MBed OS. 
```
[Error] MQTTClientMbedOs.h@116,26: expected ')' before '*' token
```
I'm using GCC_ARM, Nucleo F446RE and Generic AT-3PP

**Comment by 0xc0170** [comment]
That should not be the case, what GCC ARM version (just in case) ?

**Comment by yasir-khilji-64** [comment]
@0xc0170 I'm using Mbed CLI for Windows 
```arm-none-eabi-gcc --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437]
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by yasir-khilji-64** [comment]
Well I might be doing something wrong. 
I've cloned the repo and added it in the Mbed Project with the name mbed-mqtt. Is it right ?

**Comment by 0xc0170** [comment]
Looking at the error, this leads me to this section in the TLSSocket header:

```
#if !defined(MBED_CONF_NSAPI_OFFLOAD_TLSSOCKET) || !(MBED_CONF_NSAPI_OFFLOAD_TLSSOCKET)

// This class requires Mbed TLS SSL/TLS client code
#if defined(MBEDTLS_SSL_CLI_C) || defined(DOXYGEN_ONLY)

// class here declared
```

What's your configuration, is TLSSocket actually available ?

**Comment by yasir-khilji-64** [comment]
Well right now, I'm not using the TLSSocket. 
I'm just compiling the MQTTClientMbedOS.h library. 
Here is my mbed_app.json 
```
{
    "config": {
        "sock-type": "TCP",
        "echo-server-hostname": {
            "help": "Echo server host name.",
            "value": "\"echo.mbedcloudtesting.com\""
        },
        "echo-server-port": {
            "help": "Echo server port number.",
            "value": 7
        },
        "trace-level": {
            "help": "Options are TRACE_LEVEL_ERROR,TRACE_LEVEL_WARN,TRACE_LEVEL_INFO,TRACE_LEVEL_DEBUG",
            "macro_name": "MBED_TRACE_MAX_LEVEL",
            "value": "TRACE_LEVEL_INFO"
        }
  },
    "target_overrides": {
        "*": {
            "mbed-mqtt.max-connections": "5",
            "mbed-mqtt.max-packet-size": "1024",
            "target.network-default-interface-type": "CELLULAR",
            "mbed-trace.enable": true,
            "lwip.ipv4-enabled": true,
            "lwip.ipv6-enabled": false,
            "lwip.ethernet-enabled": false,
            "lwip.ppp-enabled": true,
            "lwip.tcp-enabled": true,
            "platform.stdio-convert-newlines": true,
            "platform.stdio-baud-rate": 115200,
            "platform.default-serial-baud-rate": 115200,
            "platform.stdio-buffered-serial": true,
            "cellular.debug-at": true,
            "nsapi.default-cellular-sim-pin": null,
            "nsapi.default-cellular-plmn": "\"41004\"",
            "nsapi.default-cellular-apn": "\"zonginternet\"",
            "nsapi.default-cellular-username": null,
            "nsapi.default-cellular-password": null,
            "GENERIC_AT3GPP.provide-default": true,
            "GENERIC_AT3GPP.tx": "PC_10",
            "GENERIC_AT3GPP.rx": "PC_11",
            "GENERIC_AT3GPP.baudrate": 115200
        },
        "DISCO_L496AG": {
            "target.macros_add": [
                "CELLULAR_DEVICE=STModCellular"
            ],
            "target.components_add": ["STMOD_CELLULAR"],
            "stmod_cellular.provide-default": "true"
        }
    }
}
```

**Comment by yasir-khilji-64** [comment]
Please add proper ifdefines around 
```MQTTClient(TLSSocket *_socket);
MQTTClient(DTLSSocket *_socket);```

**Comment by yasir-khilji-64** [comment]
Please add proper #ifdefines around the following functions 
```
MQTTClient(TLSSocket *_socket);
MQTTClient(DTLSSocket *_socket);
```

**Comment by yasir-khilji-64** [comment]
TLSSocket not working with MQTTClient. 
code snippet 
```
TLSSocket *socket = new TLSSocket;
MQTTClient client(socket);
retcode = socket->open(nwk.iface);
```
Error Logs
```
[Error] main.cpp@25,1: 'TLSSocket' does not name a type
[Error] main.cpp@26,19: 'socket' was not declared in this scope
[Error] main.cpp@59,15: 'socket' was not declared in this scope
```

**Comment by strange-v** [comment]
Seem nothing been changed from the last comment. I have the same issue

> [Error] MQTTClientMbedOs.h@116,16: unknown type name 'TLSSocket'; did you mean 'TCPSocket'?
> [Error] MQTTClientMbedOs.h@116,5: constructor cannot be redeclared
> [Error] MQTTClientMbedOs.h@130,16: unknown type name 'DTLSSocket'; did you mean 'TCPSocket'?
> [Error] MQTTClientMbedOs.h@130,5: constructor cannot be redeclared
> [Error] MQTTClientMbedOs.cpp@73,24: unknown type name 'TLSSocket'; did you mean 'TCPSocket'?
> [Error] MQTTClientMbedOs.cpp@73,13: redefinition of 'MQTTClient'
> [Error] MQTTClientMbedOs.cpp@87,24: unknown type name 'DTLSSocket'; did you mean 'TCPSocket'?
> [ERROR] In file included from .\mbed-mqtt\src\MQTTClientMbedOs.cpp:18:
> ./mbed-mqtt/src/MQTTClientMbedOs.h:116:16: error: unknown type name 'TLSSocket'; did you mean 'TCPSocket'?
> MQTTClient(TLSSocket *_socket);

Mbed OS 5.4.12
STM32F411CEU6 blue pill

Any suggestions on how to fix this?

**Comment by yasir-khilji-64** [comment]
@strange-v try using Preprocess Guards.

**Comment by yasir-khilji-64** [comment]
@0xc0170 how to implement setDefaultMessageHandler?

**Comment by drewsed** [comment]
@strange-v uncomment the following lines in `MQTTClientMbedOs.h and .cpp`:
118 `MQTTClient(TLSSocket *_socket);`
and
132 `MQTTClient(DTLSSocket *_socket);`
and the respective function bodies in the .cpp file.

After that it compiles. 

side note:
As I know you are Using WIZnetInterface, there is also a conflict with the CONNECT enum value. Either you change two occurences in the WIZnet lib, or you change about 5 occurenses of CONNECT in the MQTT lib.

**Comment by strange-v** [comment]
@drewsed, thank you, I've already compiled this lib, though it is better to fix it correctly in the repository (rename or use c++ like enums, use ifdef for TLS, etc).

I'm getting memory overflow on the blue pill, so currently I have no idea whether it works or no.

**Comment by drewsed** [comment]
@strange-v you are right fixing the library is the proper way! this was just for quick help. glad you already compiled.

so you are trying to get MQTT running on bluepill with w5500 am I right?
Mabe over TLS Sockets in future? 

what kind of memory overflow do you suffer? A MbedOS fault handler error on serial?

**Comment by strange-v** [comment]
Blue pill + W5500, correct.
TLS is not required in my case.

Yes, I'm getting the error "operator new[] out of memory" via serial. I'll try your code.
Also, I'm going to order a different board for my experiments (Chinese analog of Seeed Arch Max).

**Comment by drewsed** [comment]
I also thought about using other hardware. In my case a custom board with ESP32 and W5500 , which is working great with Arduino.

**Comment by strange-v** [comment]
@drewsed it is easy with Arduino but I want to learn something except it, Mbed looks quite promising even with all these issues.

I've tried this example and it works, as an alternative I think of modifying MQTTClient lib to work via WIZnetInterface.

**Comment by drewsed** [comment]
@strange-v great. did you use this MQTT lib for testing or the shipped one from the example?

Now i will start debugging the yield function. My code is simply publishing something every 1 second and is doing this for 10 to 15 mins. Because of the fact that MQTTClient::yield is not working with WIZnetInterface, I guess that there is the issue for the whole connection fail after few minutes.

**Comment by drewsed** [comment]
@strange-v For now it is working for me, with the described drawbacks in terms of blocking/delay. I added a new Issue for this, because its kinda off topic now. See #12

**Comment by michalpasztamobica** [comment]
Hi @yasir-khilji-64 and @drewsed , @strange-v ,
Reading through the comments it sounds like the library does not compile on platforms which don't enable TLS? Is that still the case? Do I understand correctly?

@0xc0170 , @AnttiKauppila  I wonder if we could configure this project to generate internal JIRA tickets, so we have better visibility?

**Comment by drewsed** [comment]
@michalpasztamobica you understood correctly.
I read somwhere (sorry can't find it right now) that TLS is not included by default on mbed. You have to define something like `MBEDTLS_SHA1_C` somewhere in the mbed *.json files. But i did not get it to work... maybe this will help you in some way.

**Comment by yasir-khilji-64** [comment]
Well figured it out, you can disable entropy sources for boards that don't support TLS by default.

**Comment by yasir-khilji-64** [comment]
@0xc0170 Well it is working OK now, but I need to set a default message handler and it is giving errors. Can you suggest how to do it?

**Comment by michalpasztamobica** [comment]
@yasir-khilji-64 , if you mean the MQTT message handlers, perhaps you could take a look at the way we did it in our tests.
[Here's a message handler](https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/TESTS/mqtt/mqtt/main.cpp#L277).
[Here's how we use it](https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/TESTS/mqtt/mqtt/mqtt_new.cpp#L60).

**Comment by yasir-khilji-64** [comment]
Well this is the subscribe method. 
I want to use this 
https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/src/MQTTClientMbedOs.cpp#L203

**Comment by 0xc0170** [comment]
> @0xc0170 , @AnttiKauppila I wonder if we could configure this project to generate internal JIRA tickets, so we have better visibility?

@michalpasztamobica please request it via email, it is quick to add a new repo

**Comment by michalpasztamobica** [comment]
@yasir-khilji-64 , we haven't covered this one with any tests yet. I will take care of this, hopefully within the next couple of days.

**Comment by yasir-khilji-64** [comment]
Great. Thanks.

**Comment by yasir-khilji-64** [comment]
@michalpasztamobica @0xc0170, I'm having some issue in MQTTClient object in class
```class MQTTS {
    public:
        MQTTS();
        nsapi_error_t init_mqtt(NetworkInterface* interface);
        void thread_yield();
        void messageReceived(MQTT::MessageData &md);

    private:
        TLSSocket *socket = new TLSSocket;
        MQTTClient client(socket);```

**Comment by yasir-khilji-64** [comment]
Error 
```[Error] MQTTS.h@73,27: 'socket' is not a type
[Error] MQTTS.cpp@72,11: '((MQTTS*)this)->MQTTS::client' does not have class type
[Error] MQTTS.cpp@84,11: '((MQTTS*)this)->MQTTS::client' does not have class type
[Error] MQTTS.cpp@95,9: '((MQTTS*)this)->MQTTS::client' does not have class type```

**Comment by michalpasztamobica** [comment]
@yasir-khilji-64 , you can't call the `MQTTClient` constructor in another class'es declaration...
```
private:
        ...
        MQTTClient client(socket); // This is a function call, in a place where function declaration is needed.
```
Perhaps you want something like this:
```
    public:
        MQTTS(Socket* sock) : client(socket) {};
        nsapi_error_t init_mqtt(NetworkInterface* interface);
        void thread_yield();
        void messageReceived(MQTT::MessageData &md);

    private:
        TLSSocket *socket = new TLSSocket;
        MQTTClient client;
```
?

**Comment by michalpasztamobica** [comment]
@yasir-khilji-64 , it took me a while, but finally I know why we did not test the `setDefaultMessageHandler` and we will not test it.

The default message handler can only be used if the client received a message that it doesn't have a handler for. But you cannot subscribe to a topic without providing a message handler for it.
So when is the default handler being used? In error scenarios - for example - your client crashed without unsubscribing from topics and the server keeps sending it some old subscriptions.
We could simulate this situation, but it's not worth the effort to test just one functionality.

So - `setDefaultMessageHandler` is not a function that will save you the hassle of providing message handlers every time you subscribe. Instead it is the handler that will be called for all kinds of "surprise messages" your MQTT client receives. @yasir-khilji-64 , did you make the same wrong assumption as I did? Does this clarify the situation and solve your issue?

**Comment by yasir-khilji-64** [comment]
@michalpasztamobica 
RE: MQTT class. 
Well this means, then we have first initialize the TLSSocket from main, and then pass it into the MQTT Class. 

RE: ```setDefaultMessageHandler.```
Well, I wanted to do this. Add a default message handler to the class and any MQTT message that comes, will be received by the handler, so that I don't have to make too many handlers. 
Is it possible.

**Comment by michalpasztamobica** [comment]
Hi @yasir-khilji-64 .
> Well this means, then we have first initialize the TLSSocket from main, and then pass it into the MQTT Class.

Yes, exactly. See our tests code for reference.

> Add a default message handler to the class and any MQTT message that comes, will be received by the handler, so that I don't have to make too many handlers.
> Is it possible.

Yes, you just define one message handler function and pass it to every `subscribe` call. This is how our tests work. There is [just one handler defined](https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/TESTS/mqtt/mqtt/main.cpp#L277). And we keep using it for all the tests (for example [here ](https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/TESTS/mqtt/mqtt/mqtt_new.cpp#L60) or [here](https://github.com/ARMmbed/mbed-mqtt/blob/c594a001b8dc54685b9dc3d05b7a9657259c75a7/TESTS/mqtt/mqtt/mqtt_tests.h#L200))
